### ISSUE TITLE
Memory Allocation Error

### ISSUE THREAD

**Issue by DeveloperAndCoder** [brenns10/lsh#12]
I believe there is a slight mistake in implementation of `realloc` function in the main.c at line 182.
Instead of:
`buffer = realloc(buffer, bufsize);`
The code should have been:
`buffer = realloc(buffer, bufsize * sizeof(char));`

**Comment by VFabricio** [comment]
sizeof(char) is guaranteed to be 1 (section 6.5.3.4 of the C standard).

**Comment by brenns10** [comment]
Yeah thanks to both of you. I can see how it may have been unintuitive but sizeof(char) is 1 so I left it out.
