### ISSUE TITLE
To express gratitude and ask a small question

### ISSUE THREAD

**Issue by helloworldwdchen** [brenns10/lsh#13]
I really enjoyed reading this tutorial, I read it all in one go, tried to write the code, and it finally ran successfully.
 But I have a small problem is that I did not find any code related to the two commands `ls` and `pwd`, but I can use them when launch the program, can you explain why?
 Finally, thank you very much for writing this tutorial, it brought me a happy afternoon.

**Comment by brenns10** [comment]
Hi @helloworldwdchen, sorry for replying so late to this. The reason that `ls` and `pwd` work in `lsh` is that they are actually external programs, not shell built in functions. The `execvp()` function we use actually looks up the program name in the directories listed in the `PATH` environment variable, and executes the first one it finds. If you run (in some other she'll like bash) `which ls`, the shell will print the full path to the program it would run. Hope that helps!

**Comment by helloworldwdchen** [comment]
Thank you very much, your reply is very helpful to me, and I think I understand what you mean.
