### ISSUE TITLE
Its not working with sftp

### ISSUE THREAD

**Issue by surjit** [brenns10/lsh#5]
I modified user to use it bash shell
usermod -s "binary" username
it does not working, when i change back usermod -s /bin/bash username

it works

**Comment by brenns10** [comment]
As the [README](https://github.com/brenns10/lsh) states, this shell is for demonstration and learning purposes only.  You shouldn't set it as your user's default shell, or use it for daily tasks like sftp.  Just stick to the tutorial and playing with the code!
