### ISSUE TITLE
exit in Child process

### ISSUE THREAD

**Issue by danghai** [brenns10/lsh#7]
Why in child process, it exits with EXIT_FAILURE ?
` if (execvp(args[0], args) == -1) {
      perror("lsh");
    }
    exit(EXIT_FAILURE); `   

I think it should be: 
`_exit(EXIT_SUCCESS);`

**Comment by brenns10** [comment]
The whole point of `exec()` is to replace the currently running process with another program. Thus, returning is by definition an error. Admittedly, the if statement confuses things a bit. But I didn't want there to visually be a code path where execution should fall through, even though putting exit within the if statement would be semantically the same, assuming your library + OS are sane.
